# Use postgres/example user/password credentials
version: '3.1'

services:
  gympass:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: gympass
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker